name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  # Esto es requerido para que **GitHub Actions** pueda escribir en el repositorio, 
  # por ejemplo, creando una nueva etiqueta (tag) o liberando (releasing) artefactos.
  contents: write
env:
  IMAGE_TAG: ${{ github.sha }} #El sha es un identificador único para cada commit


jobs:
  compile-and-test: # Esto es solo un nombre descriptivo del job (puede ser cualquier nombre)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Acá podriamos agregar un paso PRIMERO para instalar dependencias si fuera necesario,
    # y despues para compilar y generar artefactos
    # Como PHP y Js no son lenguajes compilados, no es necesario instalar nada
    # No son como Java o Node.js que requieren un proceso de construcción (build)
    # Y generan artefactos (artifacts) como archivos .jar (java) o node_modules (Node.js)


    # Instala las dependencias para tests en el runner (para PHP)
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    # Test de sintaxis PHP, si hay errores de sintaxis, el job fallará
    - name: Test Backend PHP Syntax
      run: |
        php -l ./backend/index.php
        php -l ./backend/conexao.php

    # Instala las dependencias para tests en el runner (para JS)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Instala las dependencias para tests en el runner (para JS)
    - name: Install ESLint
      run: npm install -g eslint

    # Test de sintaxis JS usando eslint, si hay errores de sintaxis, el job fallará
    - name: Test Frontend JS Syntax
      run: |
        find ./frontend -name '*.js' -exec eslint {} \;

  gitleaks-scan:
      runs-on: ubuntu-latest
      needs: compile-and-test # Esto asegura que este job se ejecute después del job de compilación y pruebas
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalación de Gitleak, sirve para detectar secretos (como contraseñas, tokens, etc.) en el código
      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v2
      
      - name: Run Gitleaks Scan
        run: |
          gitleaks detect --source ./backend --exit-code 1 # Este comando escanea el directorio backend y falla si encuentra secretos
          gitleaks detect --source ./frontend --exit-code 1 # Este comando escanea el directorio frontend y falla si encuentra secretos

  build:
    runs-on: ubuntu-latest
    needs: gitleaks-scan # Esto asegura que este job se ejecute después del job de gitleaks
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Backend PHP Image
      run: |
        docker build -t lucasmpalu/backend:${{ env.IMAGE_TAG }} -f ./backend/Dockerfile ./backend
        docker tag lucasmpalu/backend:${{ env.IMAGE_TAG }} lucasmpalu/backend:${{ env.IMAGE_TAG }}
    - name: Build Frontend Nginx Image
      run: |
        docker build -t lucasmpalu/frontend:${{ env.IMAGE_TAG }} -f ./frontend/Dockerfile ./frontend
        docker tag lucasmpalu/frontend:${{ env.IMAGE_TAG }} lucasmpalu/frontend:${{ env.IMAGE_TAG }}

    - name: Push Images
      run: |
        docker push lucasmpalus/backend:${{ env.IMAGE_TAG }}
        docker push lucasmpalus/frontend:${{ env.IMAGE_TAG }}